package br.gov.ma.seati.sindicato.enums;

public enum TpEscolaridadeEnum {

	FUNDAMENTAL, ENSINO_MEDIO_INCOMPLETO, ENSINO_MEDIO_COMPLETO, SUPERIOR_INCOMPLETO, SUPERIOR_COMPLETO, ESPECIALIZACAO, MESTRADO, DOUTORADO;
	
}
